// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/items/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/items/service.go -destination=internal/modules/items/mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	items "github.com/egeuysall/drop/internal/modules/items"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CheckPriceDrop mocks base method.
func (m *MockService) CheckPriceDrop(ctx context.Context, id, userID string) (*items.PriceDropCheck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPriceDrop", ctx, id, userID)
	ret0, _ := ret[0].(*items.PriceDropCheck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPriceDrop indicates an expected call of CheckPriceDrop.
func (mr *MockServiceMockRecorder) CheckPriceDrop(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPriceDrop", reflect.TypeOf((*MockService)(nil).CheckPriceDrop), ctx, id, userID)
}

// CreateItem mocks base method.
func (m *MockService) CreateItem(ctx context.Context, userID string, req items.CreateItemRequest) (*items.ItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, userID, req)
	ret0, _ := ret[0].(*items.ItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockServiceMockRecorder) CreateItem(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockService)(nil).CreateItem), ctx, userID, req)
}

// DeleteItem mocks base method.
func (m *MockService) DeleteItem(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockServiceMockRecorder) DeleteItem(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockService)(nil).DeleteItem), ctx, id, userID)
}

// GetItemByID mocks base method.
func (m *MockService) GetItemByID(ctx context.Context, id, userID string) (*items.ItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByID", ctx, id, userID)
	ret0, _ := ret[0].(*items.ItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByID indicates an expected call of GetItemByID.
func (mr *MockServiceMockRecorder) GetItemByID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByID", reflect.TypeOf((*MockService)(nil).GetItemByID), ctx, id, userID)
}

// GetItemsDueForCheck mocks base method.
func (m *MockService) GetItemsDueForCheck(ctx context.Context) ([]items.ItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsDueForCheck", ctx)
	ret0, _ := ret[0].([]items.ItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsDueForCheck indicates an expected call of GetItemsDueForCheck.
func (mr *MockServiceMockRecorder) GetItemsDueForCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsDueForCheck", reflect.TypeOf((*MockService)(nil).GetItemsDueForCheck), ctx)
}

// GetPriceHistory mocks base method.
func (m *MockService) GetPriceHistory(ctx context.Context, id string, days int) ([]items.PriceHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceHistory", ctx, id, days)
	ret0, _ := ret[0].([]items.PriceHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceHistory indicates an expected call of GetPriceHistory.
func (mr *MockServiceMockRecorder) GetPriceHistory(ctx, id, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceHistory", reflect.TypeOf((*MockService)(nil).GetPriceHistory), ctx, id, days)
}

// GetPriceStats mocks base method.
func (m *MockService) GetPriceStats(ctx context.Context, id string) (*items.PriceStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceStats", ctx, id)
	ret0, _ := ret[0].(*items.PriceStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceStats indicates an expected call of GetPriceStats.
func (mr *MockServiceMockRecorder) GetPriceStats(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceStats", reflect.TypeOf((*MockService)(nil).GetPriceStats), ctx, id)
}

// ListItemsByUserID mocks base method.
func (m *MockService) ListItemsByUserID(ctx context.Context, userID string) ([]items.ItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItemsByUserID", ctx, userID)
	ret0, _ := ret[0].([]items.ItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItemsByUserID indicates an expected call of ListItemsByUserID.
func (mr *MockServiceMockRecorder) ListItemsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItemsByUserID", reflect.TypeOf((*MockService)(nil).ListItemsByUserID), ctx, userID)
}

// RefreshPrice mocks base method.
func (m *MockService) RefreshPrice(ctx context.Context, itemID, userID, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshPrice", ctx, itemID, userID, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshPrice indicates an expected call of RefreshPrice.
func (mr *MockServiceMockRecorder) RefreshPrice(ctx, itemID, userID, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshPrice", reflect.TypeOf((*MockService)(nil).RefreshPrice), ctx, itemID, userID, url)
}

// UpdateItemByID mocks base method.
func (m *MockService) UpdateItemByID(ctx context.Context, id, userID string, req items.UpdateItemRequest) (*items.ItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemByID", ctx, id, userID, req)
	ret0, _ := ret[0].(*items.ItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItemByID indicates an expected call of UpdateItemByID.
func (mr *MockServiceMockRecorder) UpdateItemByID(ctx, id, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemByID", reflect.TypeOf((*MockService)(nil).UpdateItemByID), ctx, id, userID, req)
}

// UpdateItemPrice mocks base method.
func (m *MockService) UpdateItemPrice(ctx context.Context, id, userID string, currentPrice float64, inStock bool) (*items.ItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemPrice", ctx, id, userID, currentPrice, inStock)
	ret0, _ := ret[0].(*items.ItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItemPrice indicates an expected call of UpdateItemPrice.
func (mr *MockServiceMockRecorder) UpdateItemPrice(ctx, id, userID, currentPrice, inStock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemPrice", reflect.TypeOf((*MockService)(nil).UpdateItemPrice), ctx, id, userID, currentPrice, inStock)
}
